# =============================
# environment.yaml
# =============================

num_trials: 1

# ───────────── ROOM ─────────────
build_room: true
room_size: [5.0, 5.0, 3.0]
room_wall_thickness: 0.05
floor_color: [0.6, 0.6, 0.6]
room_color: [0.8, 0.8, 0.8]

# ───────────── TABLE ─────────────
build_table: true
table_size: [1.0, 0.6, 0.75]
table_leg_radius: 0.02

# ───────────── TABLE PLACEMENT ─────────────

near_edge_padding: 0.03

# ───────────── REACH ─────────────
arm_min_reach: 0.30
arm_max_reach: 0.85
reach_safety_margin: 0.05
